### ISSUE TITLE
[Content] Can't break line on YML

### ISSUE THREAD

**Issue by abeldotam** [nuxt-ui-pro/landing#26]
Hi 👋

User of the landing template, I would like to break line on my content displayed on the FAQ module, in order to have multiple lines answer.

Since this is YAML, I've tried several common ways to do so in the `index.yml` file ([here](https://github.com/nuxt-ui-pro/landing/blob/main/content/index.yml#L162)), , i.e: 

```
      content: |+
        line1
        line2
```
```
      content: |
        line1
        line2
```

```
      content: >
        line1
        line2
```
```
      content: "Hey\
        line 1\n\n line 2"
```

etc.

None of these work and I'm running out of ideas for breaking line on my displayed content.
Am I missing something or is it an issue with the template, or eventually Nuxt Content?

Feel free to let me know if something is incorrect.

**Comment by benjamincanac** [comment]
If you want to use markdown syntax, you might need to use the `MDC` component to display it correctly. Here is an example:

```ts
<ULandingFAQ :items="page.faq.items" multiple>
    <template #item="{ item }">
      <MDC :value="item.content" class="prose prose-primary dark:prose-invert max-w-none text-gray-500 dark:text-gray-400" />
    </template>
</ULandingFAQ>
```

**Comment by abeldotam** [comment]
Awesome, it worked like a charm, thanks! ☺️
