### ISSUE TITLE
Accessibility: Elements with visible text labels do not have matching accessible names

### ISSUE THREAD

**Issue by pschaub** [nuxt-ui-pro/landing#4]
Visible text labels that do not match the accessible name can result in a confusing experience for screen reader users. [Learn more about accessible names](https://dequeuniversity.com/rules/axe/4.7/label-content-name-mismatch).

![image](https://github.com/nuxt-ui-pro/landing/assets/11846736/d43bddb0-38fa-47ed-b652-2800cdecaf24)

**Comment by benjamincanac** [comment]
This has already been fixed upstream in `@nuxt/ui-pro` and will be available on next release.
